### PR TITLE
New hybrid dispatcher concept (enables mirai cancellation)

### PR DESCRIPTION
**Pull request by shikokuchuo**
**New default dispatcher**

Inviting @jcheng5 @hadley for review and comment.

This is a complete re-design of dispatcher using a more optimal and future-proof architecture.

The key difference is that whereas previously dispatcher used one socket *per* daemon connection, it now uses one socket for *all* daemon connections.

The previous configuration was necessary due to limitations of the NNG req/rep (PRC) protocol using a round-robin algorithm. This is typically optimal behaviour for web servers and similar applications, but not for arbitrary execution where evaluation times may vary greatly.

The novel solution is to preserve the req/rep abstraction for the user, with `mirai()` working substantially the same way, but to re-wire the dispatcher / daemon back-end to use an alternative protocol (NNG's pair 1 poly). This allows one-to-many mapping with directed sends, which is exactly what's needed to implement an optimal task queue dispatcher.

**Mirai Cancellation**

Allows actual cancellation of mirai when using `stop_mirai()`, as per the below example:
- `stop_mirai()` returns `TRUE` if the task is awaiting execution - it is discarded from the queue. Cancellation is certain.
- `stop_mirai()` returns `NA` if the task was in-execution. An interrupt is sent to the daemon process, but it may have been partially executed by this point.
- `stop_mirai()` returns `FALSE` if the task has already completed or been cancelled.

``` r
library(mirai)
daemons(2, output = TRUE)
#> [1] 2
m1 <- mirai({Sys.sleep(1); print("mirai 1 done")})
m2 <- mirai({Sys.sleep(1); print("mirai 2 done")})
m3 <- mirai({Sys.sleep(1); print("mirai 3 done")})
Sys.sleep(0.1)
(stop_mirai(m3))
#> [1] TRUE
(stop_mirai(m2))
#> [1] NA
(stop_mirai(m2))
#> [1] FALSE
#> [1] "mirai 1 done"
```
<sup>Created on 2024-12-01 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

**Other notable improvements**

- Only one (IPC) socket connection from host to dispatcher (previously there was an additional control socket for sending information requests).
- For distributed computing, plain TCP connections can be used without the added overhead of the websocket layer, as only one URL is required no matter how many daemons. We also don't need to manage many URLs and ensure a one-to-one mapping of each.
- Connection changes tracked efficiently and accurately (due to upgrades at `nanonext`) hence retiring a lot of custom code that was designed to deal with this.
- Connected daemons can be scaled up and down freely without limit (we had to set a maximum before).
- More succinct and intuitive status summary, for example (borrowing the above example):

``` r
library(mirai)
daemons(2, output = TRUE)
#> [1] 2
m1 <- mirai({Sys.sleep(1); print("mirai 1 done")})
m2 <- mirai({Sys.sleep(1); print("mirai 2 done")})
m3 <- mirai({Sys.sleep(1); print("mirai 3 done")})
Sys.sleep(0.1)
status()
#> $connections
#> [1] 2
#> 
#> $daemons
#> [1] "abstract://595b781203f9cad1ea0f39f8"
#> 
#> $mirai
#>  awaiting executing completed 
#>         1         2         0
```

<sup>Created on 2024-12-01 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

### CODE REVIEW

**Comment by hadley** [comment]
I have no comments on the implementation, but I wonder if you might want to consider returning a string rather than a `TRUE`/`FALSE`/`NA` as it's easy to write something like `if (mirai_stop(...)) ...` and forget to handle the `NA`.

**Comment by shikokuchuo** [comment]
> I have no comments on the implementation, but I wonder if you might want to consider returning a string rather than a `TRUE`/`FALSE`/`NA` as it's easy to write something like `if (mirai_stop(...)) ...` and forget to handle the `NA`.

Thanks, I was fully expecting either you or Joe to pick up on this. I wanted to show that it was possible to make this distinction. But actually this is perhaps not so useful for the user, as you can never know if a task will end up in the queue, and hence you'd always need to handle a non-certain cancellation.

As the cancellation model is fundamentally [uncooperative](https://github.com/shikokuchuo/mirai/issues/112#issue-2253212952), I think we can just offer a `TRUE`/`FALSE`, where we caveat that a `TRUE` (covering the current `TRUE`/`NA`) means that a cancellation *request* was successful but doesn't guarantee anything about the cancellation itself. We don't do this, but just noting that even if we confirmed an interrupt was successful, we wouldn't know at what point it interrupted and what ran before that.

**Comment by shikokuchuo** [comment]
I should probably add a little more on the cancellation implementation itself.

R is single-threaded, so the only way of stopping evaluation is through an interrupt signal. This must be delivered concurrent with the evaluation, i.e. from another thread. Fortunately NNG, as a concurrency framework, provides these, and we just re-purpose an async message receive [callback](https://github.com/shikokuchuo/nanonext/blob/4814abd0d47977ead3773da44e1e00f4a6c45e0a/src/core.c#L126-L150) for this purpose (in much the same way a callback can make a call into `later` and resolve a promise). This way we can send interrupts to any connected peer (not just on the local machine).

Then at the daemon (worker) we just have a [second async receive](https://github.com/shikokuchuo/mirai/pull/170/files#diff-9e809582679952a93b9f34755bb38207471945eb36cedb9e2aa755125449f531R140) ready while we're evaluating, which will raise an interrupt if a cancellation message is received.

The actual cancellation instruction is sent from [`stop_mirai()`](https://github.com/shikokuchuo/mirai/pull/170/files#diff-1fc8c45f3b61b79a3f3790faf795d9876ca781e0e5f8c0f2c23277b5d5491c7dR418) - where the payload is an integer zero followed by the message ID. The zero sentinel triggers [this branch](https://github.com/shikokuchuo/mirai/pull/170/files#diff-e5d4780f494dba83cc4ff5bd287bd550b96896b632b4e530786f2dcd89892dfbR145-R166) of dispatcher to run, which finds the `msgid` and either discards it if in the in-queue or sends a message to the relevant daemon if it's already being executed.

**Comment by shikokuchuo** [comment]
I've implemented my [suggestion above](https://github.com/shikokuchuo/mirai/pull/170#issuecomment-2513920930) in [dd30542](https://github.com/shikokuchuo/mirai/pull/170/commits/dd3054222d3b33b045286a137407f23b40641acf), so `stop_mirai()` now returns either `TRUE` or `FALSE`. As I think the `if (stop_mirai(...))` idiom is probably useful to have.

**Comment by shikokuchuo** [comment]
@jcheng5 I'll keep this open, but you can assume that I'll merge it as is (barring further comments from yourself/Hadley).

I'll defer to you what you think is the best way of making `stop_mirai()` available in Shiny. If it helps to do something on my end just let me know. For example, I can easily keep a reference to the mirai in the promise constructor [here](https://github.com/shikokuchuo/mirai/blob/main/R/promises.R#L91) by adding something like:
```r
promise[["mirai"]] <- x
```
If you're making changes to the promises package, please also take a look at  https://github.com/rstudio/promises/pull/111 where I've provided suggestions you can adopt directly in your PR there.

**Pull request merged**
