### PR TITLE
Switch vignette engine to litedown

### PR DESCRIPTION
**Pull request by shikokuchuo**
Thanks @yihui.

### CODE REVIEW

**Comment by yihui** [comment]
My pleasure!

**Comment by shikokuchuo** [comment]
It's perfect for these pre-computed vignettes.

**Comment by yihui** [comment]
Out of curiosity, how did you pre-compute these vignettes? I don't see a Makefile or a shell script.

BTW, you can use the extension `.md` for the pre-computed output files. The advantage is that Github will render `.md` files so readers can easily read them. **litedown** recognizes both `.Rmd` and `.md` as vignette source files.

**Comment by shikokuchuo** [comment]
There I 'cheat' and use `knitr` in an R script: https://github.com/shikokuchuo/mirai/blob/main/vignettes/precompile.R Thanks for the `.md` tip - I'm aware of the rendering benefits for GitHub, but I think most people will consume via `pkgdown`, and there it seems it only picks up `*.Rmd` files.

**Comment by yihui** [comment]
Oh I see. Thanks for the explanation!

**Pull request merged**
